# Generated by Django 3.1.2 on 2021-02-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
